{{- if .Values.activityService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.activityService.name }}
  labels:
    app: {{ .Values.activityService.name }}
spec:
  replicas: {{ .Values.activityService.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.activityService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.activityService.name }}
    spec:
      containers:
        - name: {{ .Values.activityService.name }}
          image: "{{ .Values.activityService.image.repository }}:{{ .Values.activityService.image.tag }}"
          imagePullPolicy: {{ .Values.activityService.image.pullPolicy }}
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.env.springProfilesActive }}
            - name: SPRING_CLOUD_CONFIG_URI
              value: "http://{{ .Values.configServer.name }}:{{ .Values.configServer.service.port }}"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://{{ .Values.eurekaServer.name }}:{{ .Values.eurekaServer.service.port }}/eureka/"
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: uri
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
            - name: SPRING_RABBITMQ_USERNAME
              value: {{ .Values.rabbitmq.auth.username }}
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: password
          resources:
            {{- toYaml .Values.activityService.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.activityService.name }}
spec:
  type: {{ .Values.activityService.service.type }}
  ports:
    - port: {{ .Values.activityService.service.port }}
      targetPort: 8083
  selector:
    app: {{ .Values.activityService.name }}
{{- end }}
