{{- if .Values.configServer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.configServer.name }}
  labels:
    app: {{ .Values.configServer.name }}
spec:
  replicas: {{ .Values.configServer.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.configServer.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.configServer.name }}
    spec:
      containers:
        - name: {{ .Values.configServer.name }}
          image: "{{ .Values.configServer.image.repository }}:{{ .Values.configServer.image.tag }}"
          imagePullPolicy: {{ .Values.configServer.image.pullPolicy }}
          ports:
            - containerPort: 8888
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.env.springProfilesActive }}
          resources:
            {{- toYaml .Values.configServer.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            initialDelaySeconds: 30
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.configServer.name }}
spec:
  type: {{ .Values.configServer.service.type }}
  ports:
    - port: {{ .Values.configServer.service.port }}
      targetPort: 8888
  selector:
    app: {{ .Values.configServer.name }}
{{- end }}
